GET http://{{ip}}:3000/member/point
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJfaWQiOjEsImlhdCI6MTY0NzU3MTk5NywiZXhwIjoxNjQ3NjU4Mzk3fQ.Wfo21PwoprINTXleDmsEbxOWIDuk4ICTxatsQ5XseJ8
Content-Type: application/json
